class_name GameEnums
extends Node

## MONDAY, TUESDAY, WEDNESDAY, THURSDAY, FRIDAY
enum WeekDay {MONDAY, TUESDAY, WEDNESDAY, THURSDAY, FRIDAY}
## SUNNY, RAINY, HAIL, SNOWY, WINDY, CLOUDY
enum Weather {SUNNY, RAINY, HAIL, SNOWY, WINDY, CLOUDY}
## CHRISTMAS, THANKSGIVING, EASTER, FOURTH_OF_JULY, NEW_YEARS
enum Holidays {CHRISTMAS, THANKSGIVING, EASTER, FOURTH_OF_JULY, NEW_YEARS}
## FAMILY, FRIENDS, COWORKERS_COLLEAGUES, COMPANIES_GOODS_SERVICES_EMPLOYEES, STRANGERS
enum Category {FAMILY, FRIENDS, COWORKERS_COLLEAGUES, COMPANIES_GOODS_SERVICES_EMPLOYEES, STRANGERS}
## CASUAL, SERIOUS, EMERGENCY
enum Severity {CASUAL, SERIOUS, EMERGENCY}
